language: php
phps:
  - 5.3
script: cd tests && phpunit .
notifications:
  irc: "irc.freenode.org#semanticscuttle"

before_script:
  - mysql -e 'create database semanticscuttle_test;'
  - mysql semanticscuttle_test < data/tables.sql
  - cat data/config.php.dist | sed "s/'username'/'root'/" | sed "s/'password'/''/" | sed "s/'scuttle'/'semanticscuttle_test'/" | sed "s/'mysql4'/'mysqli'/" > data/config.php
  - pyrus install pear/HTTP_Request2
  - pyrus install pear/PEAR
  - pyrus install pear/Stream_Var
  - phpenv rehash
